module Activesupport
  module TaggedLogging
    VERSION: String
    # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  end
end

module ActiveSupport
  module TaggedLogging
    module Formatter
      module Version
        VERSION: String
      end
      VERSION: String
    end
  end

  module TaggedLoggingVersion
    VERSION: String
  end
end
